services:
  postgres:
    image: postgres:16
    container_name: liveklass-postgres
    environment:
      POSTGRES_DB: liveklass
      POSTGRES_USER: liveklass
      POSTGRES_PASSWORD: liveklass
    ports:
      - "5432:5432"
    volumes:
      - liveklass-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liveklass -d liveklass" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  liveklass-postgres-data:
